// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"example/ent/article"
	"example/ent/articletag"
	"example/ent/predicate"
	"example/ent/tag"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ArticleTagUpdate is the builder for updating ArticleTag entities.
type ArticleTagUpdate struct {
	config
	hooks     []Hook
	mutation  *ArticleTagMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ArticleTagUpdate builder.
func (atu *ArticleTagUpdate) Where(ps ...predicate.ArticleTag) *ArticleTagUpdate {
	atu.mutation.Where(ps...)
	return atu
}

// SetTagID sets the "tag_id" field.
func (atu *ArticleTagUpdate) SetTagID(i int) *ArticleTagUpdate {
	atu.mutation.SetTagID(i)
	return atu
}

// SetNillableTagID sets the "tag_id" field if the given value is not nil.
func (atu *ArticleTagUpdate) SetNillableTagID(i *int) *ArticleTagUpdate {
	if i != nil {
		atu.SetTagID(*i)
	}
	return atu
}

// SetArticleID sets the "article_id" field.
func (atu *ArticleTagUpdate) SetArticleID(i int) *ArticleTagUpdate {
	atu.mutation.SetArticleID(i)
	return atu
}

// SetNillableArticleID sets the "article_id" field if the given value is not nil.
func (atu *ArticleTagUpdate) SetNillableArticleID(i *int) *ArticleTagUpdate {
	if i != nil {
		atu.SetArticleID(*i)
	}
	return atu
}

// SetArticle sets the "article" edge to the Article entity.
func (atu *ArticleTagUpdate) SetArticle(a *Article) *ArticleTagUpdate {
	return atu.SetArticleID(a.ID)
}

// SetTag sets the "tag" edge to the Tag entity.
func (atu *ArticleTagUpdate) SetTag(t *Tag) *ArticleTagUpdate {
	return atu.SetTagID(t.ID)
}

// Mutation returns the ArticleTagMutation object of the builder.
func (atu *ArticleTagUpdate) Mutation() *ArticleTagMutation {
	return atu.mutation
}

// ClearArticle clears the "article" edge to the Article entity.
func (atu *ArticleTagUpdate) ClearArticle() *ArticleTagUpdate {
	atu.mutation.ClearArticle()
	return atu
}

// ClearTag clears the "tag" edge to the Tag entity.
func (atu *ArticleTagUpdate) ClearTag() *ArticleTagUpdate {
	atu.mutation.ClearTag()
	return atu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (atu *ArticleTagUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, atu.sqlSave, atu.mutation, atu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (atu *ArticleTagUpdate) SaveX(ctx context.Context) int {
	affected, err := atu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (atu *ArticleTagUpdate) Exec(ctx context.Context) error {
	_, err := atu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (atu *ArticleTagUpdate) ExecX(ctx context.Context) {
	if err := atu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (atu *ArticleTagUpdate) check() error {
	if atu.mutation.ArticleCleared() && len(atu.mutation.ArticleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ArticleTag.article"`)
	}
	if atu.mutation.TagCleared() && len(atu.mutation.TagIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ArticleTag.tag"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (atu *ArticleTagUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ArticleTagUpdate {
	atu.modifiers = append(atu.modifiers, modifiers...)
	return atu
}

func (atu *ArticleTagUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := atu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(articletag.Table, articletag.Columns, sqlgraph.NewFieldSpec(articletag.FieldTagID, field.TypeInt), sqlgraph.NewFieldSpec(articletag.FieldArticleID, field.TypeInt))
	if ps := atu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if atu.mutation.ArticleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   articletag.ArticleTable,
			Columns: []string{articletag.ArticleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := atu.mutation.ArticleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   articletag.ArticleTable,
			Columns: []string{articletag.ArticleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if atu.mutation.TagCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   articletag.TagTable,
			Columns: []string{articletag.TagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := atu.mutation.TagIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   articletag.TagTable,
			Columns: []string{articletag.TagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(atu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, atu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{articletag.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	atu.mutation.done = true
	return n, nil
}

// ArticleTagUpdateOne is the builder for updating a single ArticleTag entity.
type ArticleTagUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ArticleTagMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetTagID sets the "tag_id" field.
func (atuo *ArticleTagUpdateOne) SetTagID(i int) *ArticleTagUpdateOne {
	atuo.mutation.SetTagID(i)
	return atuo
}

// SetNillableTagID sets the "tag_id" field if the given value is not nil.
func (atuo *ArticleTagUpdateOne) SetNillableTagID(i *int) *ArticleTagUpdateOne {
	if i != nil {
		atuo.SetTagID(*i)
	}
	return atuo
}

// SetArticleID sets the "article_id" field.
func (atuo *ArticleTagUpdateOne) SetArticleID(i int) *ArticleTagUpdateOne {
	atuo.mutation.SetArticleID(i)
	return atuo
}

// SetNillableArticleID sets the "article_id" field if the given value is not nil.
func (atuo *ArticleTagUpdateOne) SetNillableArticleID(i *int) *ArticleTagUpdateOne {
	if i != nil {
		atuo.SetArticleID(*i)
	}
	return atuo
}

// SetArticle sets the "article" edge to the Article entity.
func (atuo *ArticleTagUpdateOne) SetArticle(a *Article) *ArticleTagUpdateOne {
	return atuo.SetArticleID(a.ID)
}

// SetTag sets the "tag" edge to the Tag entity.
func (atuo *ArticleTagUpdateOne) SetTag(t *Tag) *ArticleTagUpdateOne {
	return atuo.SetTagID(t.ID)
}

// Mutation returns the ArticleTagMutation object of the builder.
func (atuo *ArticleTagUpdateOne) Mutation() *ArticleTagMutation {
	return atuo.mutation
}

// ClearArticle clears the "article" edge to the Article entity.
func (atuo *ArticleTagUpdateOne) ClearArticle() *ArticleTagUpdateOne {
	atuo.mutation.ClearArticle()
	return atuo
}

// ClearTag clears the "tag" edge to the Tag entity.
func (atuo *ArticleTagUpdateOne) ClearTag() *ArticleTagUpdateOne {
	atuo.mutation.ClearTag()
	return atuo
}

// Where appends a list predicates to the ArticleTagUpdate builder.
func (atuo *ArticleTagUpdateOne) Where(ps ...predicate.ArticleTag) *ArticleTagUpdateOne {
	atuo.mutation.Where(ps...)
	return atuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (atuo *ArticleTagUpdateOne) Select(field string, fields ...string) *ArticleTagUpdateOne {
	atuo.fields = append([]string{field}, fields...)
	return atuo
}

// Save executes the query and returns the updated ArticleTag entity.
func (atuo *ArticleTagUpdateOne) Save(ctx context.Context) (*ArticleTag, error) {
	return withHooks(ctx, atuo.sqlSave, atuo.mutation, atuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (atuo *ArticleTagUpdateOne) SaveX(ctx context.Context) *ArticleTag {
	node, err := atuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (atuo *ArticleTagUpdateOne) Exec(ctx context.Context) error {
	_, err := atuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (atuo *ArticleTagUpdateOne) ExecX(ctx context.Context) {
	if err := atuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (atuo *ArticleTagUpdateOne) check() error {
	if atuo.mutation.ArticleCleared() && len(atuo.mutation.ArticleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ArticleTag.article"`)
	}
	if atuo.mutation.TagCleared() && len(atuo.mutation.TagIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ArticleTag.tag"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (atuo *ArticleTagUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ArticleTagUpdateOne {
	atuo.modifiers = append(atuo.modifiers, modifiers...)
	return atuo
}

func (atuo *ArticleTagUpdateOne) sqlSave(ctx context.Context) (_node *ArticleTag, err error) {
	if err := atuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(articletag.Table, articletag.Columns, sqlgraph.NewFieldSpec(articletag.FieldTagID, field.TypeInt), sqlgraph.NewFieldSpec(articletag.FieldArticleID, field.TypeInt))
	if id, ok := atuo.mutation.TagID(); !ok {
		return nil, &ValidationError{Name: "tag_id", err: errors.New(`ent: missing "ArticleTag.tag_id" for update`)}
	} else {
		_spec.Node.CompositeID[0].Value = id
	}
	if id, ok := atuo.mutation.ArticleID(); !ok {
		return nil, &ValidationError{Name: "article_id", err: errors.New(`ent: missing "ArticleTag.article_id" for update`)}
	} else {
		_spec.Node.CompositeID[1].Value = id
	}
	if fields := atuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, len(fields))
		for i, f := range fields {
			if !articletag.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			_spec.Node.Columns[i] = f
		}
	}
	if ps := atuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if atuo.mutation.ArticleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   articletag.ArticleTable,
			Columns: []string{articletag.ArticleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := atuo.mutation.ArticleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   articletag.ArticleTable,
			Columns: []string{articletag.ArticleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if atuo.mutation.TagCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   articletag.TagTable,
			Columns: []string{articletag.TagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := atuo.mutation.TagIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   articletag.TagTable,
			Columns: []string{articletag.TagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(atuo.modifiers...)
	_node = &ArticleTag{config: atuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, atuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{articletag.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	atuo.mutation.done = true
	return _node, nil
}
