// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"example/ent/department"
	"example/ent/employee"
	"example/ent/predicate"
	"example/ent/user"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EmployeeUpdate is the builder for updating Employee entities.
type EmployeeUpdate struct {
	config
	hooks     []Hook
	mutation  *EmployeeMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the EmployeeUpdate builder.
func (eu *EmployeeUpdate) Where(ps ...predicate.Employee) *EmployeeUpdate {
	eu.mutation.Where(ps...)
	return eu
}

// SetHireDate sets the "hire_date" field.
func (eu *EmployeeUpdate) SetHireDate(t time.Time) *EmployeeUpdate {
	eu.mutation.SetHireDate(t)
	return eu
}

// SetNillableHireDate sets the "hire_date" field if the given value is not nil.
func (eu *EmployeeUpdate) SetNillableHireDate(t *time.Time) *EmployeeUpdate {
	if t != nil {
		eu.SetHireDate(*t)
	}
	return eu
}

// SetManagerID sets the "manager_id" field.
func (eu *EmployeeUpdate) SetManagerID(i int) *EmployeeUpdate {
	eu.mutation.SetManagerID(i)
	return eu
}

// SetNillableManagerID sets the "manager_id" field if the given value is not nil.
func (eu *EmployeeUpdate) SetNillableManagerID(i *int) *EmployeeUpdate {
	if i != nil {
		eu.SetManagerID(*i)
	}
	return eu
}

// ClearManagerID clears the value of the "manager_id" field.
func (eu *EmployeeUpdate) ClearManagerID() *EmployeeUpdate {
	eu.mutation.ClearManagerID()
	return eu
}

// SetUserID sets the "user_id" field.
func (eu *EmployeeUpdate) SetUserID(i int) *EmployeeUpdate {
	eu.mutation.SetUserID(i)
	return eu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (eu *EmployeeUpdate) SetNillableUserID(i *int) *EmployeeUpdate {
	if i != nil {
		eu.SetUserID(*i)
	}
	return eu
}

// SetDepartmentID sets the "department_id" field.
func (eu *EmployeeUpdate) SetDepartmentID(i int) *EmployeeUpdate {
	eu.mutation.SetDepartmentID(i)
	return eu
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (eu *EmployeeUpdate) SetNillableDepartmentID(i *int) *EmployeeUpdate {
	if i != nil {
		eu.SetDepartmentID(*i)
	}
	return eu
}

// SetUser sets the "user" edge to the User entity.
func (eu *EmployeeUpdate) SetUser(u *User) *EmployeeUpdate {
	return eu.SetUserID(u.ID)
}

// SetDepartment sets the "department" edge to the Department entity.
func (eu *EmployeeUpdate) SetDepartment(d *Department) *EmployeeUpdate {
	return eu.SetDepartmentID(d.ID)
}

// SetManager sets the "manager" edge to the Employee entity.
func (eu *EmployeeUpdate) SetManager(e *Employee) *EmployeeUpdate {
	return eu.SetManagerID(e.ID)
}

// AddReportIDs adds the "reports" edge to the Employee entity by IDs.
func (eu *EmployeeUpdate) AddReportIDs(ids ...int) *EmployeeUpdate {
	eu.mutation.AddReportIDs(ids...)
	return eu
}

// AddReports adds the "reports" edges to the Employee entity.
func (eu *EmployeeUpdate) AddReports(e ...*Employee) *EmployeeUpdate {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return eu.AddReportIDs(ids...)
}

// Mutation returns the EmployeeMutation object of the builder.
func (eu *EmployeeUpdate) Mutation() *EmployeeMutation {
	return eu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (eu *EmployeeUpdate) ClearUser() *EmployeeUpdate {
	eu.mutation.ClearUser()
	return eu
}

// ClearDepartment clears the "department" edge to the Department entity.
func (eu *EmployeeUpdate) ClearDepartment() *EmployeeUpdate {
	eu.mutation.ClearDepartment()
	return eu
}

// ClearManager clears the "manager" edge to the Employee entity.
func (eu *EmployeeUpdate) ClearManager() *EmployeeUpdate {
	eu.mutation.ClearManager()
	return eu
}

// ClearReports clears all "reports" edges to the Employee entity.
func (eu *EmployeeUpdate) ClearReports() *EmployeeUpdate {
	eu.mutation.ClearReports()
	return eu
}

// RemoveReportIDs removes the "reports" edge to Employee entities by IDs.
func (eu *EmployeeUpdate) RemoveReportIDs(ids ...int) *EmployeeUpdate {
	eu.mutation.RemoveReportIDs(ids...)
	return eu
}

// RemoveReports removes "reports" edges to Employee entities.
func (eu *EmployeeUpdate) RemoveReports(e ...*Employee) *EmployeeUpdate {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return eu.RemoveReportIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (eu *EmployeeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, eu.sqlSave, eu.mutation, eu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (eu *EmployeeUpdate) SaveX(ctx context.Context) int {
	affected, err := eu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (eu *EmployeeUpdate) Exec(ctx context.Context) error {
	_, err := eu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eu *EmployeeUpdate) ExecX(ctx context.Context) {
	if err := eu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (eu *EmployeeUpdate) check() error {
	if eu.mutation.UserCleared() && len(eu.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Employee.user"`)
	}
	if eu.mutation.DepartmentCleared() && len(eu.mutation.DepartmentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Employee.department"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (eu *EmployeeUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *EmployeeUpdate {
	eu.modifiers = append(eu.modifiers, modifiers...)
	return eu
}

func (eu *EmployeeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := eu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(employee.Table, employee.Columns, sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt))
	if ps := eu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := eu.mutation.HireDate(); ok {
		_spec.SetField(employee.FieldHireDate, field.TypeTime, value)
	}
	if eu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   employee.UserTable,
			Columns: []string{employee.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := eu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   employee.UserTable,
			Columns: []string{employee.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if eu.mutation.DepartmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.DepartmentTable,
			Columns: []string{employee.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := eu.mutation.DepartmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.DepartmentTable,
			Columns: []string{employee.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if eu.mutation.ManagerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   employee.ManagerTable,
			Columns: []string{employee.ManagerColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := eu.mutation.ManagerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   employee.ManagerTable,
			Columns: []string{employee.ManagerColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if eu.mutation.ReportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   employee.ReportsTable,
			Columns: []string{employee.ReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := eu.mutation.RemovedReportsIDs(); len(nodes) > 0 && !eu.mutation.ReportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   employee.ReportsTable,
			Columns: []string{employee.ReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := eu.mutation.ReportsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   employee.ReportsTable,
			Columns: []string{employee.ReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(eu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, eu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{employee.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	eu.mutation.done = true
	return n, nil
}

// EmployeeUpdateOne is the builder for updating a single Employee entity.
type EmployeeUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *EmployeeMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetHireDate sets the "hire_date" field.
func (euo *EmployeeUpdateOne) SetHireDate(t time.Time) *EmployeeUpdateOne {
	euo.mutation.SetHireDate(t)
	return euo
}

// SetNillableHireDate sets the "hire_date" field if the given value is not nil.
func (euo *EmployeeUpdateOne) SetNillableHireDate(t *time.Time) *EmployeeUpdateOne {
	if t != nil {
		euo.SetHireDate(*t)
	}
	return euo
}

// SetManagerID sets the "manager_id" field.
func (euo *EmployeeUpdateOne) SetManagerID(i int) *EmployeeUpdateOne {
	euo.mutation.SetManagerID(i)
	return euo
}

// SetNillableManagerID sets the "manager_id" field if the given value is not nil.
func (euo *EmployeeUpdateOne) SetNillableManagerID(i *int) *EmployeeUpdateOne {
	if i != nil {
		euo.SetManagerID(*i)
	}
	return euo
}

// ClearManagerID clears the value of the "manager_id" field.
func (euo *EmployeeUpdateOne) ClearManagerID() *EmployeeUpdateOne {
	euo.mutation.ClearManagerID()
	return euo
}

// SetUserID sets the "user_id" field.
func (euo *EmployeeUpdateOne) SetUserID(i int) *EmployeeUpdateOne {
	euo.mutation.SetUserID(i)
	return euo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (euo *EmployeeUpdateOne) SetNillableUserID(i *int) *EmployeeUpdateOne {
	if i != nil {
		euo.SetUserID(*i)
	}
	return euo
}

// SetDepartmentID sets the "department_id" field.
func (euo *EmployeeUpdateOne) SetDepartmentID(i int) *EmployeeUpdateOne {
	euo.mutation.SetDepartmentID(i)
	return euo
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (euo *EmployeeUpdateOne) SetNillableDepartmentID(i *int) *EmployeeUpdateOne {
	if i != nil {
		euo.SetDepartmentID(*i)
	}
	return euo
}

// SetUser sets the "user" edge to the User entity.
func (euo *EmployeeUpdateOne) SetUser(u *User) *EmployeeUpdateOne {
	return euo.SetUserID(u.ID)
}

// SetDepartment sets the "department" edge to the Department entity.
func (euo *EmployeeUpdateOne) SetDepartment(d *Department) *EmployeeUpdateOne {
	return euo.SetDepartmentID(d.ID)
}

// SetManager sets the "manager" edge to the Employee entity.
func (euo *EmployeeUpdateOne) SetManager(e *Employee) *EmployeeUpdateOne {
	return euo.SetManagerID(e.ID)
}

// AddReportIDs adds the "reports" edge to the Employee entity by IDs.
func (euo *EmployeeUpdateOne) AddReportIDs(ids ...int) *EmployeeUpdateOne {
	euo.mutation.AddReportIDs(ids...)
	return euo
}

// AddReports adds the "reports" edges to the Employee entity.
func (euo *EmployeeUpdateOne) AddReports(e ...*Employee) *EmployeeUpdateOne {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return euo.AddReportIDs(ids...)
}

// Mutation returns the EmployeeMutation object of the builder.
func (euo *EmployeeUpdateOne) Mutation() *EmployeeMutation {
	return euo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (euo *EmployeeUpdateOne) ClearUser() *EmployeeUpdateOne {
	euo.mutation.ClearUser()
	return euo
}

// ClearDepartment clears the "department" edge to the Department entity.
func (euo *EmployeeUpdateOne) ClearDepartment() *EmployeeUpdateOne {
	euo.mutation.ClearDepartment()
	return euo
}

// ClearManager clears the "manager" edge to the Employee entity.
func (euo *EmployeeUpdateOne) ClearManager() *EmployeeUpdateOne {
	euo.mutation.ClearManager()
	return euo
}

// ClearReports clears all "reports" edges to the Employee entity.
func (euo *EmployeeUpdateOne) ClearReports() *EmployeeUpdateOne {
	euo.mutation.ClearReports()
	return euo
}

// RemoveReportIDs removes the "reports" edge to Employee entities by IDs.
func (euo *EmployeeUpdateOne) RemoveReportIDs(ids ...int) *EmployeeUpdateOne {
	euo.mutation.RemoveReportIDs(ids...)
	return euo
}

// RemoveReports removes "reports" edges to Employee entities.
func (euo *EmployeeUpdateOne) RemoveReports(e ...*Employee) *EmployeeUpdateOne {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return euo.RemoveReportIDs(ids...)
}

// Where appends a list predicates to the EmployeeUpdate builder.
func (euo *EmployeeUpdateOne) Where(ps ...predicate.Employee) *EmployeeUpdateOne {
	euo.mutation.Where(ps...)
	return euo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (euo *EmployeeUpdateOne) Select(field string, fields ...string) *EmployeeUpdateOne {
	euo.fields = append([]string{field}, fields...)
	return euo
}

// Save executes the query and returns the updated Employee entity.
func (euo *EmployeeUpdateOne) Save(ctx context.Context) (*Employee, error) {
	return withHooks(ctx, euo.sqlSave, euo.mutation, euo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (euo *EmployeeUpdateOne) SaveX(ctx context.Context) *Employee {
	node, err := euo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (euo *EmployeeUpdateOne) Exec(ctx context.Context) error {
	_, err := euo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (euo *EmployeeUpdateOne) ExecX(ctx context.Context) {
	if err := euo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (euo *EmployeeUpdateOne) check() error {
	if euo.mutation.UserCleared() && len(euo.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Employee.user"`)
	}
	if euo.mutation.DepartmentCleared() && len(euo.mutation.DepartmentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Employee.department"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (euo *EmployeeUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *EmployeeUpdateOne {
	euo.modifiers = append(euo.modifiers, modifiers...)
	return euo
}

func (euo *EmployeeUpdateOne) sqlSave(ctx context.Context) (_node *Employee, err error) {
	if err := euo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(employee.Table, employee.Columns, sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt))
	id, ok := euo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Employee.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := euo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, employee.FieldID)
		for _, f := range fields {
			if !employee.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != employee.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := euo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := euo.mutation.HireDate(); ok {
		_spec.SetField(employee.FieldHireDate, field.TypeTime, value)
	}
	if euo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   employee.UserTable,
			Columns: []string{employee.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := euo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   employee.UserTable,
			Columns: []string{employee.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if euo.mutation.DepartmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.DepartmentTable,
			Columns: []string{employee.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := euo.mutation.DepartmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.DepartmentTable,
			Columns: []string{employee.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if euo.mutation.ManagerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   employee.ManagerTable,
			Columns: []string{employee.ManagerColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := euo.mutation.ManagerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   employee.ManagerTable,
			Columns: []string{employee.ManagerColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if euo.mutation.ReportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   employee.ReportsTable,
			Columns: []string{employee.ReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := euo.mutation.RemovedReportsIDs(); len(nodes) > 0 && !euo.mutation.ReportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   employee.ReportsTable,
			Columns: []string{employee.ReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := euo.mutation.ReportsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   employee.ReportsTable,
			Columns: []string{employee.ReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(euo.modifiers...)
	_node = &Employee{config: euo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, euo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{employee.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	euo.mutation.done = true
	return _node, nil
}
