// Code generated by ent, DO NOT EDIT.

package ent

import (
	"example/ent/article"
	"example/ent/user"
	"example/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	articleFields := schema.Article{}.Fields()
	_ = articleFields
	// articleDescPublished is the schema descriptor for published field.
	articleDescPublished := articleFields[3].Descriptor()
	// article.DefaultPublished holds the default value on creation for the published field.
	article.DefaultPublished = articleDescPublished.Default.(bool)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescIsActive is the schema descriptor for is_active field.
	userDescIsActive := userFields[3].Descriptor()
	// user.DefaultIsActive holds the default value on creation for the is_active field.
	user.DefaultIsActive = userDescIsActive.Default.(bool)
}
