// Code generated by ent, DO NOT EDIT.

package ent

import (
	"e2e/ent/teststate"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// TestState is the model entity for the TestState schema.
type TestState struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Key holds the value of the "key" field.
	Key string `json:"key,omitempty"`
	// Done holds the value of the "done" field.
	Done         bool `json:"done,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TestState) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case teststate.FieldDone:
			values[i] = new(sql.NullBool)
		case teststate.FieldID:
			values[i] = new(sql.NullInt64)
		case teststate.FieldKey:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TestState fields.
func (ts *TestState) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case teststate.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ts.ID = int(value.Int64)
		case teststate.FieldKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key", values[i])
			} else if value.Valid {
				ts.Key = value.String
			}
		case teststate.FieldDone:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field done", values[i])
			} else if value.Valid {
				ts.Done = value.Bool
			}
		default:
			ts.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TestState.
// This includes values selected through modifiers, order, etc.
func (ts *TestState) Value(name string) (ent.Value, error) {
	return ts.selectValues.Get(name)
}

// Update returns a builder for updating this TestState.
// Note that you need to call TestState.Unwrap() before calling this method if this TestState
// was returned from a transaction, and the transaction was committed or rolled back.
func (ts *TestState) Update() *TestStateUpdateOne {
	return NewTestStateClient(ts.config).UpdateOne(ts)
}

// Unwrap unwraps the TestState entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ts *TestState) Unwrap() *TestState {
	_tx, ok := ts.config.driver.(*txDriver)
	if !ok {
		panic("ent: TestState is not a transactional entity")
	}
	ts.config.driver = _tx.drv
	return ts
}

// String implements the fmt.Stringer.
func (ts *TestState) String() string {
	var builder strings.Builder
	builder.WriteString("TestState(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ts.ID))
	builder.WriteString("key=")
	builder.WriteString(ts.Key)
	builder.WriteString(", ")
	builder.WriteString("done=")
	builder.WriteString(fmt.Sprintf("%v", ts.Done))
	builder.WriteByte(')')
	return builder.String()
}

// TestStates is a parsable slice of TestState.
type TestStates []*TestState
