// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"e2e/ent/teststate"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TestStateCreate is the builder for creating a TestState entity.
type TestStateCreate struct {
	config
	mutation *TestStateMutation
	hooks    []Hook
}

// SetKey sets the "key" field.
func (tsc *TestStateCreate) SetKey(s string) *TestStateCreate {
	tsc.mutation.SetKey(s)
	return tsc
}

// SetDone sets the "done" field.
func (tsc *TestStateCreate) SetDone(b bool) *TestStateCreate {
	tsc.mutation.SetDone(b)
	return tsc
}

// Mutation returns the TestStateMutation object of the builder.
func (tsc *TestStateCreate) Mutation() *TestStateMutation {
	return tsc.mutation
}

// Save creates the TestState in the database.
func (tsc *TestStateCreate) Save(ctx context.Context) (*TestState, error) {
	return withHooks(ctx, tsc.sqlSave, tsc.mutation, tsc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tsc *TestStateCreate) SaveX(ctx context.Context) *TestState {
	v, err := tsc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tsc *TestStateCreate) Exec(ctx context.Context) error {
	_, err := tsc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tsc *TestStateCreate) ExecX(ctx context.Context) {
	if err := tsc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tsc *TestStateCreate) check() error {
	if _, ok := tsc.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "TestState.key"`)}
	}
	if _, ok := tsc.mutation.Done(); !ok {
		return &ValidationError{Name: "done", err: errors.New(`ent: missing required field "TestState.done"`)}
	}
	return nil
}

func (tsc *TestStateCreate) sqlSave(ctx context.Context) (*TestState, error) {
	if err := tsc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tsc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tsc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	tsc.mutation.id = &_node.ID
	tsc.mutation.done = true
	return _node, nil
}

func (tsc *TestStateCreate) createSpec() (*TestState, *sqlgraph.CreateSpec) {
	var (
		_node = &TestState{config: tsc.config}
		_spec = sqlgraph.NewCreateSpec(teststate.Table, sqlgraph.NewFieldSpec(teststate.FieldID, field.TypeInt))
	)
	if value, ok := tsc.mutation.Key(); ok {
		_spec.SetField(teststate.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := tsc.mutation.Done(); ok {
		_spec.SetField(teststate.FieldDone, field.TypeBool, value)
		_node.Done = value
	}
	return _node, _spec
}

// TestStateCreateBulk is the builder for creating many TestState entities in bulk.
type TestStateCreateBulk struct {
	config
	err      error
	builders []*TestStateCreate
}

// Save creates the TestState entities in the database.
func (tscb *TestStateCreateBulk) Save(ctx context.Context) ([]*TestState, error) {
	if tscb.err != nil {
		return nil, tscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tscb.builders))
	nodes := make([]*TestState, len(tscb.builders))
	mutators := make([]Mutator, len(tscb.builders))
	for i := range tscb.builders {
		func(i int, root context.Context) {
			builder := tscb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TestStateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tscb *TestStateCreateBulk) SaveX(ctx context.Context) []*TestState {
	v, err := tscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tscb *TestStateCreateBulk) Exec(ctx context.Context) error {
	_, err := tscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tscb *TestStateCreateBulk) ExecX(ctx context.Context) {
	if err := tscb.Exec(ctx); err != nil {
		panic(err)
	}
}
