// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"e2e/ent/predicate"
	"e2e/ent/teststate"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TestStateUpdate is the builder for updating TestState entities.
type TestStateUpdate struct {
	config
	hooks     []Hook
	mutation  *TestStateMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the TestStateUpdate builder.
func (tsu *TestStateUpdate) Where(ps ...predicate.TestState) *TestStateUpdate {
	tsu.mutation.Where(ps...)
	return tsu
}

// SetKey sets the "key" field.
func (tsu *TestStateUpdate) SetKey(s string) *TestStateUpdate {
	tsu.mutation.SetKey(s)
	return tsu
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (tsu *TestStateUpdate) SetNillableKey(s *string) *TestStateUpdate {
	if s != nil {
		tsu.SetKey(*s)
	}
	return tsu
}

// SetDone sets the "done" field.
func (tsu *TestStateUpdate) SetDone(b bool) *TestStateUpdate {
	tsu.mutation.SetDone(b)
	return tsu
}

// SetNillableDone sets the "done" field if the given value is not nil.
func (tsu *TestStateUpdate) SetNillableDone(b *bool) *TestStateUpdate {
	if b != nil {
		tsu.SetDone(*b)
	}
	return tsu
}

// Mutation returns the TestStateMutation object of the builder.
func (tsu *TestStateUpdate) Mutation() *TestStateMutation {
	return tsu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tsu *TestStateUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, tsu.sqlSave, tsu.mutation, tsu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tsu *TestStateUpdate) SaveX(ctx context.Context) int {
	affected, err := tsu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tsu *TestStateUpdate) Exec(ctx context.Context) error {
	_, err := tsu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tsu *TestStateUpdate) ExecX(ctx context.Context) {
	if err := tsu.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (tsu *TestStateUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TestStateUpdate {
	tsu.modifiers = append(tsu.modifiers, modifiers...)
	return tsu
}

func (tsu *TestStateUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(teststate.Table, teststate.Columns, sqlgraph.NewFieldSpec(teststate.FieldID, field.TypeInt))
	if ps := tsu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tsu.mutation.Key(); ok {
		_spec.SetField(teststate.FieldKey, field.TypeString, value)
	}
	if value, ok := tsu.mutation.Done(); ok {
		_spec.SetField(teststate.FieldDone, field.TypeBool, value)
	}
	_spec.AddModifiers(tsu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, tsu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teststate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tsu.mutation.done = true
	return n, nil
}

// TestStateUpdateOne is the builder for updating a single TestState entity.
type TestStateUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *TestStateMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetKey sets the "key" field.
func (tsuo *TestStateUpdateOne) SetKey(s string) *TestStateUpdateOne {
	tsuo.mutation.SetKey(s)
	return tsuo
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (tsuo *TestStateUpdateOne) SetNillableKey(s *string) *TestStateUpdateOne {
	if s != nil {
		tsuo.SetKey(*s)
	}
	return tsuo
}

// SetDone sets the "done" field.
func (tsuo *TestStateUpdateOne) SetDone(b bool) *TestStateUpdateOne {
	tsuo.mutation.SetDone(b)
	return tsuo
}

// SetNillableDone sets the "done" field if the given value is not nil.
func (tsuo *TestStateUpdateOne) SetNillableDone(b *bool) *TestStateUpdateOne {
	if b != nil {
		tsuo.SetDone(*b)
	}
	return tsuo
}

// Mutation returns the TestStateMutation object of the builder.
func (tsuo *TestStateUpdateOne) Mutation() *TestStateMutation {
	return tsuo.mutation
}

// Where appends a list predicates to the TestStateUpdate builder.
func (tsuo *TestStateUpdateOne) Where(ps ...predicate.TestState) *TestStateUpdateOne {
	tsuo.mutation.Where(ps...)
	return tsuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tsuo *TestStateUpdateOne) Select(field string, fields ...string) *TestStateUpdateOne {
	tsuo.fields = append([]string{field}, fields...)
	return tsuo
}

// Save executes the query and returns the updated TestState entity.
func (tsuo *TestStateUpdateOne) Save(ctx context.Context) (*TestState, error) {
	return withHooks(ctx, tsuo.sqlSave, tsuo.mutation, tsuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tsuo *TestStateUpdateOne) SaveX(ctx context.Context) *TestState {
	node, err := tsuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tsuo *TestStateUpdateOne) Exec(ctx context.Context) error {
	_, err := tsuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tsuo *TestStateUpdateOne) ExecX(ctx context.Context) {
	if err := tsuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (tsuo *TestStateUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TestStateUpdateOne {
	tsuo.modifiers = append(tsuo.modifiers, modifiers...)
	return tsuo
}

func (tsuo *TestStateUpdateOne) sqlSave(ctx context.Context) (_node *TestState, err error) {
	_spec := sqlgraph.NewUpdateSpec(teststate.Table, teststate.Columns, sqlgraph.NewFieldSpec(teststate.FieldID, field.TypeInt))
	id, ok := tsuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TestState.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tsuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, teststate.FieldID)
		for _, f := range fields {
			if !teststate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != teststate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tsuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tsuo.mutation.Key(); ok {
		_spec.SetField(teststate.FieldKey, field.TypeString, value)
	}
	if value, ok := tsuo.mutation.Done(); ok {
		_spec.SetField(teststate.FieldDone, field.TypeBool, value)
	}
	_spec.AddModifiers(tsuo.modifiers...)
	_node = &TestState{config: tsuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tsuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teststate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tsuo.mutation.done = true
	return _node, nil
}
